name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Checkout code
        uses: actions/checkout@v5

      - name: buildprod
        run: ./scripts/buildprod.sh

      - name: Set up Cloud SDK
        run: "google-github-actions/setup-gcloud@v2"

      - name: Build and submit
        run: gcloud builds submit --tag REGION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG .
