name: cd

on:
  push:
    branches: [main]

jobs:
  cd:
    name: cd
    runs-on: ubuntu-lastest

    steps:
      - name: Chewckout code
        uses: actions/checkout@v5

      - name: Set up Go toolchain
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Build the app
        run: docker build -t lyrania/notely:latest .
